### ISSUE TITLE
An error occurred while Performance/Sum cop inspecting

### ISSUE THREAD

**Issue by hanachin** [rubocop-hq/rubocop-performance#192]
## Expected behavior

```
% echo '[].inject :+' | rubocop -r rubocop-performance --only Performance/Sum --stdin dummy.rb -d
For /home/sei/.rbenv/plugins/ruby-build: Inspecting 1 file
Scanning /home/sei/.rbenv/plugins/ruby-build/dummy.rb
C

Offenses:

dummy.rb:1:4: C: Performance/Sum: Use sum instead of inject(:+).
[].inject :+
   ^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
Finished in 0.11925876897294074 seconds
```

## Actual behavior

```
% echo '[].inject :+' | rubocop -r rubocop-performance --only Performance/Sum --stdin dummy.rb -d
For /home/sei/.rbenv/plugins/ruby-build: Inspecting 1 file
Scanning /home/sei/.rbenv/plugins/ruby-build/dummy.rb
An error occurred while Performance/Sum cop was inspecting /home/sei/.rbenv/plugins/ruby-build/dummy.rb:1:0.
undefined method `end_pos' for nil:NilClass
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.8.1/lib/rubocop/cop/performance/sum.rb:78:in `sum_method_range'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.8.1/lib/rubocop/cop/performance/sum.rb:45:in `block in on_send'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.8.1/lib/rubocop/cop/performance/sum.rb:52:in `sum_candidate?'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-performance-1.8.1/lib/rubocop/cop/performance/sum.rb:44:in `on_send'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:166:in `with_cop_error_handling'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:99:in `block in trigger_responding_cops'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:98:in `each'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:98:in `trigger_responding_cops'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:69:in `on_send'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-ast-1.1.1/lib/rubocop/ast/traversal.rb:20:in `walk'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/commissioner.rb:86:in `investigate'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/team.rb:157:in `investigate_partial'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cop/team.rb:83:in `investigate'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:315:in `inspect_file'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:259:in `block in do_inspection_loop'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:293:in `block in iterate_until_no_changes'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:286:in `loop'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:286:in `iterate_until_no_changes'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:255:in `do_inspection_loop'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:132:in `block in file_offenses'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:157:in `file_offense_cache'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:131:in `file_offenses'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:122:in `process_file'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:100:in `each'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:100:in `reduce'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:100:in `each_inspected_file'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:86:in `inspect_files'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/runner.rb:47:in `run'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli/command/execute_runner.rb:25:in `execute_runner'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli/command/execute_runner.rb:17:in `run'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli/command.rb:11:in `run'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli/environment.rb:18:in `run'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli.rb:65:in `run_command'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli.rb:72:in `execute_runners'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/lib/rubocop/cli.rb:41:in `run'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/exe/rubocop:13:in `block in <top (required)>'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
/home/sei/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rubocop-1.2.0/exe/rubocop:12:in `<top (required)>'
/home/sei/.rbenv/versions/2.7.2/bin/rubocop:23:in `load'
/home/sei/.rbenv/versions/2.7.2/bin/rubocop:23:in `<main>'
.

1 file inspected, no offenses detected

1 error occurred:
An error occurred while Performance/Sum cop was inspecting /home/sei/.rbenv/plugins/ruby-build/dummy.rb:1:0.
Errors are usually caused by RuboCop bugs.
Please, report your problems to RuboCop's issue tracker.
https://github.com/rubocop-hq/rubocop/issues

Mention the following information in the issue report:
1.2.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.7.2 x86_64-linux)
Finished in 0.12126243801321834 seconds
```

## Steps to reproduce the problem

```
echo '[].inject :+' | rubocop -r rubocop-performance --only Performance/Sum --stdin dummy.rb -d
```

## RuboCop version

```
% rubocop -V
1.2.0 (using Parser 2.7.2.0, rubocop-ast 1.1.1, running on ruby 2.7.2 x86_64-linux)
```

**Comment by koic** [comment]
This issue has been fixed in the master branch. I will cut the next version of RuboCop Performance in a few days. Please wait a moment. Thank you.

**Comment by koic** [comment]
@hanachin Thank you for waiting. RuboCop Performance 1.9.0 has been released!
