### ISSUE TITLE
uninitialized constant RuboCop::Cop::Performance::Count::SafeMode

### ISSUE THREAD

**Issue by alexandru-calinoiu** [rubocop-hq/rubocop-performance#85]
## Expected behavior

Expect `rubocop -a` on a non-rails project to work.

## Actual behavior

```
uninitialized constant RuboCop::Cop::Performance::Count::SafeMode
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:41:in `<class:Count>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:40:in `<module:Performance>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:5:in `<module:Cop>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:4:in `<module:RuboCop>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:3:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance_cops.rb:7:in `require_relative'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance_cops.rb:7:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop-performance.rb:11:in `require_relative'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop-performance.rb:11:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader_resolver.rb:15:in `require'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader_resolver.rb:11:in `each'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader.rb:45:in `load_file'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_loader.rb:86:in `configuration_from_file'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/config_store.rb:44:in `for'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/cli.rb:120:in `apply_default_formatter'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/lib/rubocop/cli.rb:40:in `run'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/exe/rubocop:13:in `block in <top (required)>'
/home/user/.rvm/rubies/ruby-2.6.4/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-0.77.0/exe/rubocop:12:in `<top (required)>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/bin/rubocop:23:in `load'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/bin/rubocop:23:in `<main>'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/bin/ruby_executable_hooks:24:in `eval'
/home/user/.rvm/gems/ruby-2.6.4@.tour3/bin/ruby_executable_hooks:24:in `<main>'
```

## Steps to reproduce the problem

Run `rubocop` on a non-rails app with rubocop version 0.77

## RuboCop version

```
$ [bundle exec] rubocop -V
0.77.0 (using Parser 2.6.5.0, running on ruby 2.6.4 x86_64-linux)
```

**Comment by koic** [comment]
> /home/user/.rvm/gems/ruby-2.6.4@.tour3/gems/rubocop-performance-1.4.1/lib/rubocop/cop/performance/count.rb:41:in `<class:Count>'

RuboCop Performance 1.5.1 has been released. Can you update the gem? I think this issue will be resolved by applying the following changes:
https://github.com/rubocop-hq/rubocop-performance/blob/master/CHANGELOG.md#changes

**Comment by alexandru-calinoiu** [comment]
Indeed that was the issue,
